sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - 8'
  - 10
after_success:
  - npx run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
